#### general settings
name: GAT_MTCausal_MIMIC3_RMDL
train_type: causal-gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  name: mimic3
  dataset_path: "./data/mimic3_objects/mimic3_dp.pkl"
  graph_path: "./data/graphs/mimic3_dp.pkl"
  pretrained: "./data/graphs/mimic3_dp_ptr.pkl"
  labels_path: "./data/graphs/mimic3_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic3_dp_entity_mapping.pkl"
#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GAT_Causal_MIMIC3_READM"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005 # Learning rate
  weight_decay: 0

#### GNN settings
GNN:
  name: "GAT"
  num_layers: 2
  in_dim: 128
  hidden_dim: 128
  out_dim: 351
  attn_drop: 0.1
  feat_drop: 0.1
  num_heads: 8
  num_out_heads: 1
  negative_slope: 0.1

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 1000
  batch_size: 4096
  causal: True
  reg: 0.001
  n_samples: 2000
  temperature: 0.005

#### logging settings:
logging:
  tags: [
    "MIMIC3",
    "MT",
    "Pretrained"
  ]
  mode: online # offline, disabled, online