#### general settings
name: GIN_Causal_MIMIC3
train_type: causal-gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  dataset_path: "./data/mimic3_objects/mimic3_dp.pkl"
  graph_path: "./data/graphs/mimic3_dp.pkl"
  labels_path: "./data/graphs/mimic3_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic3_dp_entity_mapping.pkl"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GIN_Causal_MIMIC3_RML"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001 # Learning rate
  weight_decay: 0.001

#### GNN settings
GNN:
  name: "GIN"
  num_layers: 1
  num_mlp_layers: 1
  in_dim: 128
  hidden_dim: 256
  out_dim: 2
  feat_drop: 0.2

  neighbor_pooling_type: mean

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 500
  batch_size: 4096
