#### general settings
name: GIN_MTCausal_MIMIC4_RMDL
train_type: causal-gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  name: mimic4
  dataset_path: "./data/mimic3_objects/mimic4_dp.pkl"
  graph_path: "./data/graphs/mimic4_dp.pkl"
  pretrained: "./data/graphs/mimic4_dp_ptr.pkl"
  labels_path: "./data/graphs/mimic4_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic4_dp_entity_mapping.pkl"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/GIN_Causal_MIMIC3_RMDL"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005 # Learning rate
  weight_decay: 0

#### GNN settings
GNN:
  name: "GIN"
  num_layers: 2
  num_mlp_layers: 1
  in_dim: 128
  hidden_dim: 64
  out_dim: 506
  feat_drop: 0.1

  neighbor_pooling_type: mean

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 1000
  batch_size: 4096
  causal: True
  reg: 0.001
  n_samples: 2000
  temperature: 0.005

#### logging settings:
logging:
  tags: [
    "MIMIC3",
    "MT",
    "Pretrained"
  ]
  mode: online # offline, disabled, online