#### general settings
name: HGT_MTCausal_MIMIC4_RMDL
train_type: causal-gnn
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  name: mimic4
  dataset_path: "./data/mimic3_objects/mimic4_dp.pkl"
  graph_path: "./data/graphs/mimic4_dp.pkl"
  pretrained: "./data/graphs/mimic4_dp_ptr.pkl"
  labels_path: "./data/graphs/mimic4_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic4_dp_entity_mapping.pkl"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/HGT_Causal_MIMIC4_RMDL"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.006 # Learning rate
  weight_decay: 0

#### GNN settings
GNN:
  name: "HGT"
  num_layers: 2
  in_dim: 128
  hidden_dim: 64
  out_dim: 506
  num_heads: 16

  num_out_heads: 1
  feat_drop: 0.05

#### training settings: learning rate scheme, loss, optimizer
train:
  tasks: [
    "mort_pred",
    "los",
    "drug_rec",
    "readm"
  ]
  num_epochs: 1000
  batch_size: 4096
  causal: True
  reg: 0.00005
  n_samples: 2000
  temperature: 0.005

#### logging settings:
logging:
  tags: [
    "MIMIC4",
    "MT"
  ]
  mode: online # offline, disabled, online