#### general settings
name: HGT_ST_MIMIC3_RMDL
train_type: causal-gnn-st
eval_type: homo-graph
gpu_ids: '0'

#### datasets
datasets:
  name: mimic3
  dataset_path: "./data/mimic3_objects/mimic3_dp.pkl"
  graph_path: "./data/graphs/mimic3_dp.pkl"
  pretrained: "./data/graphs/mimic3_dp_ptr.pkl"
  labels_path: "./data/graphs/mimic3_dp_labels.pkl"
  entity_mapping: "./data/graphs/mimic3_dp_entity_mapping.pkl"

#### Checkpoint settings
checkpoint:
  path: "./checkpoints/HGT_ST_MIMIC3_RMLD"
  save_checkpoint_freq: 2

#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.005 # Learning rate
  weight_decay: 0

#### GNN settings
GNN:
  name: "HGT"
  num_layers: 2
  in_dim: 128
  hidden_dim: 64
  out_dim: 351
  num_heads: 2
  num_out_heads: 1
  feat_drop: 0.2

#### training settings: learning rate scheme, loss, optimizer
train:
  num_epochs: 500
  batch_size: 4096
  causal: False

#### logging settings:
logging:
  tags: [
    "MIMIC3",
    "Pretrained",
    "ST"
  ]